config/routes.rb
Rails.application.routes.draw do

  devise_for :admin,skip:[:registrations,:passwords],controllers:{
    sessions:'admin/sessions',
  }
  
    namespace :admin do
    get '/'=>'homes#top'
    get 'search' => 'homes#search', as: 'search'
    get 'customers/:customer_id/orders' => 'orders#index', as: 'customer_orders'
    resources:customers,only:[:index,:show,:edit,:update]
    # resources:items,only:[:index,:new,:create,:show,:edit,:update]
    resources :items, except: [:destroy]
    resources:genres,only:[:index,:create,:edit,:update]
    resources :orders, only: [:index, :show, :update] do
      resources :order_details, only: [:update]
    end
    # resources:orders,only:[:show,:update]
    # resources:order_details,only:[:update]
  end

  devise_for :customers,skip:[:passwords],controllers:{
    sessions:'public/sessions',
    registrations:'public/registrations'
  }

  scope module: :public do
    # controller:homes
    root to:'homes#top'
    get '/about'=>'homes#about',as:"about"
    
    # controller:customers
    get '/customers/my_page'=>'customers#show'
    get '/customers/information/edit'=>'customers#edit'
    patch 'customers/information'=>'customers#update'
    # customers/editのようにするとdeviseのルーティングと重複するため、informationを付け加えている。
    get '/customers/unsubscribe'=>'customers#unsubscribe'
    put 'customers/information' => 'customers#update'
    patch '/customers/withdraw'=>'customers#withdraw'

    # controller:addresses
    resources:addresses,only:[:index,:edit,:create,:update,:destroy]

    # controller:items
    resources:items,only:[:index,:show]

    # controller:cart_items
    delete '/cart_items/destroy_all'=>'cart_items#destroy_all'
    resources:cart_items,only:[:index,:update,:destroy,:create]

    # controller:orders
    post '/orders/confirm'=>'orders#confirm'
    get '/orders/thanks'=>'orders#thanks'
    resources:orders,only:[:new,:create,:index,:show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  # has_many :orders, dependent: :destroy
  has_many :orders
  # dependent: :destroyを削除
  has_many :cart_items, dependent: :destroy
  
  scope :only_active, -> { where(is_active: true) }
  
  # validates:name,presence:true,length:{minimum:2,maximum:20}
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :first_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  # カナは全角カタカナしか登録できなくなった
  validates :email, presence: true, uniqueness: true
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true
  validates :telephone_number, presence: true, format: { with: /\A\d{10,11}\z/ }
  
  def full_name
    last_name + " " + first_name
  end
  
  def full_name_kana
    last_name_kana + " " + first_name_kana
  end
  
  def has_in_cart(item)
    cart_items.find_by(item_id: item.id)
  end
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_customer, only: [:show, :edit, :update]
  # ensure_customerでcustomer.find(params[:id])を定義しているので、いちいち各アクションで定義する必要がない。
  
  # 顧客一覧画面
  def index
    @customers = Customer.page(params[:page]).per(10)
  end

# 顧客詳細画面
  def show
    # @customer = Customer.find(params[:id])
  end

# 顧客編集画面
  def edit
    # @customer = Customer.find(params[:id])
  end
  
  # 顧客情報
  def update
    @customer.update(customer_params) ? (redirect_to admin_customer_path(@customer)) : (render :edit)
    # もし@customerをアップデートしたらadmin_customer_pathへ、そうでなければrenderへということのよう。
    # この場合フラッシュメッセージは実装できないのかな？
    
    # @customer = Customer.find(params[:id])
    # if @customer.update(customer_params)
    #   flash[:notice]="顧客情報の変更に成功しました"
    #   redirect_to admin_customer_path(@customer.id)
    # else
    #   flash[:notice]="顧客情報の変更に失敗しました"
    #   render:update
    # end
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:email,:postal_code,:address,:telephone_number,:is_active)
  end
  # is_deletedをis_activeに変更。defaultはtrueです
  
  def ensure_customer
    @customer = Customer.find(params[:id])
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_index.html.erb
<table class="table has_border">
  <thead class="table-active">
    <th>会員ID</th>
    <th>氏名</th>
    <th>メールアドレス</th>
    <th>ステータス</th>
  </thead>
  
  <tbody>
    <% customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td>
          <%= link_to admin_customer_path(customer.id) do %>
            <%= customer.full_name %>
          <% end %>
        </td>
        <td><%= customer.email %></td>
        <td>
          <% if customer.is_active? %>
            <span class="text-active">有効</span>
          <% else %>
            <span class="text-invalid">退会</span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
  
</table>

app/views/admin/customers/edit.html.erb
<div class="container">
  <h4><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h4>
  <%= form_with model: @customer,url: admin_customer_path(@customer.id), method: :patch, local:true do |ce|%>
  <table class="table">
    <tr>
      <th>会員ID</th>
      <td><%= @customer.id %></td>
    </tr>
    <tr>
      <th>氏名</th>
      <td><%= ce.text_field:last_name %>  <%= ce.text_field:first_name %></td>
    </tr>
    <tr>
      <th>フリガナ</th>
      <td><%= ce.text_field:last_name_kana %>  <%= ce.text_field:first_name_kana %></td>
    </tr>
    <tr>
      <th>郵便番号</th>
      <td><%= ce.text_field:postal_code %></td>
    </tr>
    <tr>
      <th>住所</th>
      <td><%= ce.text_area :address,size: "50x1" %></td>
    </tr>
    <tr>
      <th>電話番号</th>
      <td><%= ce.telephone_field:telephone_number %></td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td><%= ce.email_field:email %></td>
    </tr>
    <tr>
      <th>会員ステータス</th>
      <td>
        <%= ce.radio_button:is_active, true %>
        <%= ce.label:is_active,"有効",{value:"true",style:"display:inline-block;"}%>
        <%= ce.radio_button:is_actice, false %>
        <%= ce.label:is_active,"退会",{value:"false",style:"display:inline-block;"}%>
        <!--ラジオボタンの書き方は模範回答が2行で終わってたから確認-->
      </td>
    </tr>
    <tr>
      <th></th>
      <td><%= ce.submit "変更を保存",class:'btn btn-success' %></td>
    </tr>
  </table>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <h4 class="page-title">会員一覧</h4>
  <div class="row">
    <div class="col-md-12">
      <%= render 'index', customers: @customers %>
     <!-- <table class="table mt-2">-->
     <!--  <thead class="table-active">-->
     <!--   <tr>-->
     <!--    <th>会員ID</th>-->
     <!--    <th>氏名</th>-->
     <!--    <th>メールアドレス</th>-->
     <!--    <th>ステータス</th>-->
     <!--   </tr>-->
     <!--  </thead>-->

     <!--  <tbody>-->
     <!--   <% @customers.each do |customer|%>-->
     <!--    <tr>-->
     <!--     <td><%= customer.id %></td>-->
     <!--     <td>-->
     <!--       <%= link_to admin_customer_path(customer.id) do %>-->
     <!--        <%= customer.full_name %>-->
     <!--       <% end %>-->
            <!--full_nameはCustomerモデルに定義あり-->
     <!--     </td>-->
     <!--     <td><%= customer.email %></td>-->
     <!--     <td>-->
     <!--       <% if customer.is_active? %>-->
     <!--        <p class="text-success font-weight-bold">有効</p>-->
     <!--       <% else %>-->
     <!--        <p class="text-secondary">退会</p>-->
     <!--       <% end %>-->
     <!--     </td>-->
     <!--   </tr>-->
     <!--  <% end %>-->
     <!-- </tbody>-->
     <!--</table>-->
    </div>
  </div>

 <%= paginate @customers, theme: 'twitter-bootstrap-4' %>

</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <h4 class="page-title"><%= @customer.last_name%><%= @customer.first_name %>さんの会員詳細</h4>
  <table class="table table-borderless">
    <tr>
      <th style="width: 20%">会員ID</th>
      <td><%= @customer.id %></td>
    </tr>
    <tr>
      <th>氏名</th>
      <td><%= @customer.last_name %>　<%= @customer.first_name %></td>
    </tr>
    <tr>
      <th>フリガナ</th>
      <td><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></td>
    </tr>
    <tr>
      <th>郵便番号</th>
      <td><%= @customer.postal_code.to_s.insert(3,"-") %></td>
    </tr>
    <tr>
      <th>住所</th>
      <td><%= @customer.address %></td>
    </tr>
    <tr>
      <th>電話番号</th>
      <td><%= @customer.telephone_number %></td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td><%= @customer.email %></td>
    </tr>
    <tr>
      <th>会員ステータス</th>
      <td>
        <% if @customer.is_active? %>
          <p class="text-success font-weight-bold">有効</p>
        <% else %>
          <p class="text-secondary">退会</p>
        <% end %>
      </td>
    </tr>
    <tr>
      <!--<th></th>-->
      <td><%= link_to "編集する",edit_admin_customer_path, class:'btn btn-success' %></td>
      <td><%= link_to "注文履歴一覧を見る", admin_customer_orders_path(@customer), class: "btn btn-primary" %></td>
    </tr>
  </table>
</div>