config/routes.rb
Rails.application.routes.draw do

  devise_for :admin,skip:[:registrations,:passwords],controllers:{
    sessions:'admin/sessions',
  }
  
    namespace :admin do
    get '/'=>'homes#top'
    get 'search' => 'homes#search', as: 'search'
    get 'customers/:customer_id/orders' => 'orders#index', as: 'customer_orders'
    resources:customers,only:[:index,:show,:edit,:update]
    # resources:items,only:[:index,:new,:create,:show,:edit,:update]
    resources :items, except: [:destroy]
    resources:genres,only:[:index,:create,:edit,:update]
    resources :orders, only: [:index, :show, :update] do
      resources :order_details, only: [:update]
    end
    # resources:orders,only:[:show,:update]
    # resources:order_details,only:[:update]
  end

  devise_for :customers,skip:[:passwords],controllers:{
    sessions:'public/sessions',
    registrations:'public/registrations'
  }

  scope module: :public do
    # controller:homes
    root to:'homes#top'
    get '/about'=>'homes#about',as:"about"
    
    # controller:customers
    get '/customers/my_page'=>'customers#show'
    get '/customers/information/edit'=>'customers#edit'
    patch 'customers/information'=>'customers#update'
    # customers/editのようにするとdeviseのルーティングと重複するため、informationを付け加えている。
    get '/customers/unsubscribe'=>'customers#unsubscribe'
    put 'customers/information' => 'customers#update'
    patch '/customers/withdraw'=>'customers#withdraw'

    # controller:addresses
    resources:addresses,only:[:index,:edit,:create,:update,:destroy]

    # controller:items
    resources:items,only:[:index,:show]

    # controller:cart_items
    delete '/cart_items/destroy_all'=>'cart_items#destroy_all'
    resources:cart_items,only:[:index,:update,:destroy,:create]

    # controller:orders
    post '/orders/confirm'=>'orders#confirm'
    get '/orders/thanks'=>'orders#thanks'
    resources:orders,only:[:new,:create,:index,:show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :customer
  has_many :order_details
  # dependent: :destroyを削除。注文詳細が消えたからといって注文履歴を消さなくていいやんってことかな？
  has_many :items, through: :order_details
  # 注文詳細を通じてたくさんの商品情報を有している。ということか、、
  
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true
  validates :name, presence: true
  validates :shipping_cost, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
  validates :total_payment, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
  
  scope :ordered_today, -> { where(created_at: Time.current.at_beginning_of_day..Time.current.at.end_of_day) }
  # beginning_of_dayはその日のタイムスタンプを返すactive supportのメソッド。Time.currentは「今日」。
  # つまりこれは今日のはじまりから終わりまでの間に作成されたオーダーをスコープするメソッド＝ordered_today
  
  enum payment_method:{
    credit:0,
    bank:1
  }
  
  enum status:{
    payment_waiting:0,
    payment_confirmation:1,
    in_production:2,
    preparing_deliver:3,
    deliverd:4
  }
  
  def get_shipping_informations_from(resource)
    class_name = resource.class.name
    if class_name == 'Customer'
    # resource: Customer
      self.postal_code = resource.postal_code
      self.address = resource.address
      self.name = resource.full_name
    elsif class_nae == 'Address'
    # resource: Address
      self.postal_code = resource.postal_code
      self.address = resource.address
      self.name = resource.name
    end
  end
  
  def create_order_details(customer)
    unless order_details.first
      cart_items = customer.cart_items.includes(:item)
      # includesは関連するテーブルをまとめて取得するメソッド。
      cart_items.each do |cart_item|
        item = cart_item.item
        OrderDetail.create!(
          order_id: id,
          item_id: item.id,
          order_price: item.with_tax_price,
          amount: cart_item.amount
        )
      end
      cart_items.destroy_all
    end
  end
  
  def are_all_details_completed?
    (order_details.completed.count == order_details.count) ? true : false
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_order, only: [:show, :update]
  
  def index
    if params[:customer_id]
      @customer = Customer.find(params[:customer_id])
      @orders = @customer.orders.page(params[:page]).reverse_order
    elsif params[:created_at] == "today"
      @orders = Order.ordered_today.includes(:customer).page(params[:page]).reverse_order
      # ordered_torayはOrderモデルでscope定義している
    else
      @orders = Order.includes(:customer).page(params[:page]).reverse_order
    end
  end
  
  # 注文詳細画面（ステータス編集を兼ねる）
  def show
    # @orders = Order.all
    # @order = Order.find(params[:id])
    @customer = @order.customer
    @order_details = @order.order_details.includes(:item)
  end
  
  # 注文ステータスの更新
  def update
    if @order.update(order_params) && @order.confirm_deposit?
      @order.order_details.update_all(making_status: 1)
    end
    redirect_to admin_order_path(@order)
    
    # @order = Order.find(params[:id])
    # @order_details = @order.order_details
    
    # if @order.update(order_params)
    #   flash[:notice]="注文ステータスを更新しました"
    #   @order_details.update_all(making_status: 1) if @order.status == "payment_confirmation"
    #   redirect_to admin_order_path(@order.id)
    # else
    #   flash[:alert]="注文ステータスの更新に失敗しました"
    #   render:show
    # end
  end

  private
  
  def order_params
    params.require(:order).permit(:status)
  end
  
  def ensure_order
    @order = Order.find(params[:id])
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
  <h4 class="page-title">
    <% if params[:customer_id] %>
      <%= @customer.full_name %>さんの注文履歴一覧
    <% else %>
      注文履歴一覧
    <% end %>
  </h4>
  
  <div class="row">
    <div class="col-md-10">
      <table class="table">
        <thead class="table-active">
          <tr>
            <th>注文日 </th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>総計</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order|%>
            <tr>
              <td><%= link_to order.created_at.strftime("%Y/%m/%d %H:%M:%S"), admin_order_path(order) %></td>
              <td><%= link_to order.customer.full_name, admin_customer_path(order.customer) %></td>
              <td><%= order.order_details.sum(:amount) %></td>
              <td><%= order.total_payment %></td>
              <td><%= order.status_i18n %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @orders, theme: 'twitter-bootstrap-4' %>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <h4 class="page-title">注文履歴詳細</h4>
  <div class="row">
    <div class="col-md-12">
      <%= form_with model: @order, url: admin_order_path(@order.id), method: :patch, local: true do |order|%>
      <table class="table table-borderless">
        <tr>
          <th>購入者</th>
          <td>
            <%= link_to admin_customer_path(@customer.id) do %>
             <%= @customer.full_name %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime('%Y/%m/%d')%></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>
            <%= "〒"+@order.postal_code.to_s.insert(3,"-") %>
            <%= @order.address %><br>
            <%= @order.name %>
          </td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>
            <%= order.select :status, Order.statuses_i18n.invert, {prompt: false} %>
            <%= order.submit"更新", class:'btn btn-success btn-sm' %>
          </td>
        </tr>
      </table>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-9">
      <table class="table table-bordered">
        <thead class="table-active">
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <% @order_details.each do |order_detail|%>
        <tbody>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= order_detail.item.with_tax_price %></td>
            <td><%= order_detail.amount %></td>
            <td><%= (order_detail.item.with_tax_price * order_detail.amount).to_s(:delimited) %></td>
            <td>
             <%= form_with model: order_detail, url: admin_order_detail_path(order_id: @order_id, id: order_detail.id), method: :patch, local: true do |order_detail|%>
              <%= order_detail.select :making_status, OrderDetail.making_statuses_i18n.invert, {prompt: false} %>
              <%= order_detail.submit"更新", class:'btn btn-success btn-sm'%>
             <% end %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>

    <div class="col-md-auto">
      <table class="table table-borderless">
        <tr>
          <th>商品合計</th>
          <td><%= (@order.total_payment - @order.shipping_cost).to_s(:delimited) %></td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%= @order.shipping_cost %></td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td><%= @order.total_payment.to_s(:delimited) %></td>
        </tr>
      </table>
    </div>
  </div>

</div>