config/routes.rb
Rails.application.routes.draw do

  devise_for :admin,skip:[:registrations,:passwords],controllers:{
    sessions:'admin/sessions',
  }
  
    namespace :admin do
    get '/'=>'homes#top'
    get 'search' => 'homes#search', as: 'search'
    get 'customers/:customer_id/orders' => 'orders#index', as: 'customer_orders'
    resources:customers,only:[:index,:show,:edit,:update]
    # resources:items,only:[:index,:new,:create,:show,:edit,:update]
    resources :items, except: [:destroy]
    resources:genres,only:[:index,:create,:edit,:update]
    resources :orders, only: [:index, :show, :update] do
      resources :order_details, only: [:update]
    end
    # resources:orders,only:[:show,:update]
    # resources:order_details,only:[:update]
  end

  devise_for :customers,skip:[:passwords],controllers:{
    sessions:'public/sessions',
    registrations:'public/registrations'
  }

  scope module: :public do
    # controller:homes
    root to:'homes#top'
    get '/about'=>'homes#about',as:"about"
    
    # controller:customers
    get '/customers/my_page'=>'customers#show'
    get '/customers/information/edit'=>'customers#edit'
    patch 'customers/information'=>'customers#update'
    # customers/editのようにするとdeviseのルーティングと重複するため、informationを付け加えている。
    get '/customers/unsubscribe'=>'customers#unsubscribe'
    put 'customers/information' => 'customers#update'
    patch '/customers/withdraw'=>'customers#withdraw'

    # controller:addresses
    resources:addresses,only:[:index,:edit,:create,:update,:destroy]

    # controller:items
    resources:items,only:[:index,:show]

    # controller:cart_items
    delete '/cart_items/destroy_all'=>'cart_items#destroy_all'
    resources:cart_items,only:[:index,:update,:destroy,:create]

    # controller:orders
    post '/orders/confirm'=>'orders#confirm'
    get '/orders/thanks'=>'orders#thanks'
    resources:orders,only:[:new,:create,:index,:show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  # has_many:items,dependent: :destroy
  has_many :items
  # dependet: :destroyを削除
  scope :only_active, -> { where(is_active: true) }
  # is_activeがtrueのジャンルのみ取り出すscopeメソッド
  
  validates :name, presence: true, uniqueness: true
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_genre, only: [:show, :edit, :update]
  # ensure_genreで@genre = Genre.find(params[:id])を定義しているので各アクションで定義する必要がないようだ。
  
  # ジャンル管理画面（一覧・追加を兼ねる）
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  # ジャンル新規登録
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice]="ジャンルの新規登録に成功しました"
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

# ジャンル編集画面
  def edit
    # @genre = Genre.find(params[:id])
    # ensure_genreで定義済みのため記載する必要なし
  end
  
# ジャンルデータ更新
  def update
    # @genre = Genre.find(params[:id])
    # if @genre.update(genre_params)
    #   flash[:notice]="ジャンルのデータ更新に成功しました"
    #   redirect_to admin_genres_path
    if @genre.update(genre_params)
      unless @genre.is_active
      # unlessは「unless 条件式」と書いて「条件式がfalseなら処理を実行」という意味
      # この場合、ジャンルのis_activeはデフォルトtrueのため、unlessにより「genreのis_activeがfalseの場合は」ということになる
        @genre.items.update_all(is_active: false)
        # 該当ジャンルの全アイテムのis_activeをfalseに変更
      end
      redirect_to admin_genres_path
      # ifからここまで変更
    else
      render :edit
    end
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name, :is_active)
  end
  # is_activeを追加
  
  def ensure_genre
    @genre = Genre.find(params[:id])
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <h4 class="page-title">ジャンル編集</h4>
  <div class="row">
    <div class="col-md-12">
      <%= form_with model: @genre, url: edit_admin_genre_path, local: true do |genre|%>
      <div class="form-group">
        <%= genre.label :"ジャンル名", class:"col-md-2 font-weight-bold"%>
        <%= genre.text_field :name, class:"col-md-2"%>
        <%= genre.radio_button :is_active, true %>
        <%= genre.label :is_active, "有効", class:"text-active" %>
        <%= genre.radio_button :is_active, false %>
        <%= genre.label :is_active, "無効", class:"text-invalid" %>
        <%= genre.submit "変更を保存", class:'btn btn-success ml-4'%>
      </div>
      <% end %>

    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <h4 class="page-title">ジャンル一覧・追加</h4>
  <div class="row">
    <div class="col-md-8 mt-3 ml-2">

      <%= form_with model: @genre, url: admin_genres_path, local: true do |genre| %>
      <!--模範回答にformをrenderにする書き方があるので参考にしてもよい-->
      <div class="form-group">
        <%= genre.label :"ジャンル名", class:"col-md-3 font-weight-bold"%>
        <%= genre.text_field :name, class:"col-md-3" %>
        <%= genre.radio_button :is_active, true %>
        <%= genre.label :is_active, "有効", class:"text-active" %>
        <%= genre.radio_button :is_active, false %>
        <%= genre.label :is_active, "無効", class:"text-invalid" %>
        <%= genre.submit "新規登録", class:'btn btn-success col-md-2 ml-4'%>
      </div>
      <% end %>

    </div>

    <div class="col-md-5 mt-3">
      <table class="table">
        <thead class="table-active">
          <th>ジャンル名</th>
          <th>状態</th>
          <!--ジャンルの有効ステータス表示を追加-->
          <th></th>
          <!--<th colspan="2"></th>-->
        </thead>
        <tbody>
          <% @genres.each do |genre|%>
          <tr>
            <!--<td>　<%= genre.name %></td>-->
            <td><%= link_to genre.name, admin_items_path(genre_id: genre.id), class:"underline" %></td>
            <!--ジャンルごとのアイテム一覧の表示を追加-->
            <td>
              <% if genre.is_active? %>
                <span class="text-active">有効</span>
              <% else %>
                <span class="text-invalid">無効</span>
              <% end %>
            </td>
            <td class="text-right"><%= link_to"編集する",edit_admin_genre_path(genre.id),class:'btn btn-success' %>　</td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>