config/routes.rb
Rails.application.routes.draw do

  devise_for :admin,skip:[:registrations,:passwords],controllers:{
    sessions:'admin/sessions',
  }
  
    namespace :admin do
    get '/'=>'homes#top'
    get 'search' => 'homes#search', as: 'search'
    get 'customers/:customer_id/orders' => 'orders#index', as: 'customer_orders'
    resources:customers,only:[:index,:show,:edit,:update]
    # resources:items,only:[:index,:new,:create,:show,:edit,:update]
    resources :items, except: [:destroy]
    resources:genres,only:[:index,:create,:edit,:update]
    resources :orders, only: [:index, :show, :update] do
      resources :order_details, only: [:update]
    end
    # resources:orders,only:[:show,:update]
    # resources:order_details,only:[:update]
  end

  devise_for :customers,skip:[:passwords],controllers:{
    sessions:'public/sessions',
    registrations:'public/registrations'
  }

  scope module: :public do
    # controller:homes
    root to:'homes#top'
    get '/about'=>'homes#about',as:"about"
    
    # controller:customers
    get '/customers/my_page'=>'customers#show'
    get '/customers/information/edit'=>'customers#edit'
    patch 'customers/information'=>'customers#update'
    # customers/editのようにするとdeviseのルーティングと重複するため、informationを付け加えている。
    get '/customers/unsubscribe'=>'customers#unsubscribe'
    put 'customers/information' => 'customers#update'
    patch '/customers/withdraw'=>'customers#withdraw'

    # controller:addresses
    resources:addresses,only:[:index,:edit,:create,:update,:destroy]

    # controller:items
    resources:items,only:[:index,:show]

    # controller:cart_items
    delete '/cart_items/destroy_all'=>'cart_items#destroy_all'
    resources:cart_items,only:[:index,:update,:destroy,:create]

    # controller:orders
    post '/orders/confirm'=>'orders#confirm'
    get '/orders/thanks'=>'orders#thanks'
    resources:orders,only:[:new,:create,:index,:show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/a30ba0c1da.js" crossorigin="anonymous"></script>
  </head>

  <body class="d-flex flex-column">
    <header class="shadow-sm mt-0">
      <nav class="navbar navbar-fixed-top navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <div class="navbar-brand">
            <%= link_to"ながのCAKE",root_path, style:"color:gray", class:"border border-secondary rounded p-2" %>
          </div>
          <button class="navbar-toggler" type="button" style="background-color: #696969" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expand="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <% if customer_signed_in? %>
           <span class="ml-5">ようこそ、<%= current_customer.last_name %>さん！</span>
          <% end %>

          <div class="collapse navbar-collapse flex-column" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto mb-2">
            <!--管理者ログイン時-->
              <% if admin_signed_in? %>
               <li class="nav-link">
                 <%= link_to"商品一覧",admin_items_path, style:"color:gray", class:"border border-secondary rounded p-2" %>
               </li>
               <li class="nav-link">
                 <%= link_to"会員一覧",admin_customers_path,style:"color:gray", class:"border border-secondary rounded p-2" %>
               </li>
               <li class="nav-link">
                 <%= link_to"注文履歴一覧",admin_path,style:"color:gray", class:"border border-secondary rounded p-2" %>
               </li>
               <li class="nav-link">
                 <%= link_to"ジャンル一覧",admin_genres_path,style:"color:gray", class:"border border-secondary rounded p-2" %>
               </li>
               <li class="nav-link">
                 <%= link_to"ログアウト",destroy_admin_session_path,method: :delete,style:"color:gray", class:"border border-secondary rounded p-2" %>
               </li>

            <!--顧客ログイン時-->
              <% elsif customer_signed_in? %>
               <li class="nav-link">
                 <%= link_to"マイページ",customers_my_page_path, style:"color:gray", class:"border border-secondary rounded p-2" %>
               </li>
               <li class="nav-link">
                 <%= link_to"商品一覧",items_path,style:"color:gray", class:"border border-secondary rounded p-2" %>
               </li>
               <li class="nav-link">
                 <%= link_to"カート",cart_items_path,style:"color:gray", class:"border border-secondary rounded p-2" %>
               </li>
               <li class="nav-link">
                 <%= link_to"ログアウト",destroy_customer_session_path,method: :delete,style:"color:gray", class:"border border-secondary rounded p-2" %>
               </li>
              <!--どちらもログインしていない時-->
              <% else %>
               <li class="nav-link">
                 <%= link_to"About",about_path,style:"color:gray", class:"border border-secondary rounded p-2" %>
               </li>
               <li class="nav-link">
                 <%= link_to"商品一覧",items_path,style:"color:gray", class:"border border-secondary rounded p-2" %>
               </li>
               <li class="nav-link">
                 <%= link_to"新規登録",new_customer_registration_path,style:"color:gray", class:"border border-secondary rounded p-2" %>
               </li>
               <li class="nav-link">
                 <%= link_to"ログイン",new_customer_session_path,style:"color:gray", class:"border border-secondary rounded p-2" %>
               </li>
              <% end %>
            </ul>
            
            <div class="search-form ml-auto mr-2">
            <% if admin_signed_in? %>
              <%= form_tag(admin_search_path, method: :get) do %>
                <%= text_field_tag "search[content]", "", :placeholder =>"会員: 姓,名,セイ,メイ / 商品: 商品名", size:'39x1' %>
                <%= select_tag "search[model]", options_for_select({ "会員" => "customer", "商品" => "item" }) %>
                <%= select_tag "search[method]", options_for_select({ "部分一致" => "partial", "前方一致" => "forward", "後方一致" => "backward", "完全一致" => "perfect" }) %>
                <%= submit_tag '検索', class: "btn btn-primary" %>
              <% end %>
            <% end %>
            </div>

            <!--<div class="search-form ml-auto mr-2">-->
            <!-- <form class="form-inline">-->
            <!--   <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
            <!--   <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
            <!-- </form>-->
            <!--</div>-->

          </div>
        </div>
      </nav>

    </header>

    <main class="container">
      <div class="mt-3 text-success">
        <p id="notice"><%= notice %></p>
      </div>
      <div class="mt-3 text-danger">
        <p id="alert"><%= alert %></p>
      </div>

      <%= yield %>
    </main>

    <footer class="footer mt-auto p-3 bg-light">
      <div class="container-fluid">
        <p class="text-right mt-3">
          <%= link_to "管理者ログイン",new_admin_session_path, style:"color:green", class:"border border-success rounded p-2"%>
        </p>
      </div>
    </footer>
  </body>
</html>